CREATE TABLE IF NOT EXISTS domain (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT NULL
);

CREATE TABLE IF NOT EXISTS reject_recipient (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) NOT NULL,
  domain INTEGER NOT NULL,
  description TEXT NULL,
  UNIQUE(username, domain)
);

CREATE TABLE IF NOT EXISTS reject_sender (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50),
  domain_name VARCHAR(50) NOT NULL,
  description TEXT NULL,
  UNIQUE(username, domain_name)
);

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) DEFAULT NULL,
  domain INTEGER NOT NULL,
  password VARCHAR(255) NOT NULL,
  forward_to VARCHAR(255) DEFAULT NULL,
  description TEXT NULL,
  UNIQUE(username, domain)
);
