---
- hosts: localhost
  become: yes
  name: provision
  tasks:
    - block:
      - name: start rsyslogd
        shell: rsyslogd
        ignore_errors: yes

    - include_role:
        name: host
      when: run is not defined
    - include_role:
        name: ssl
      when: run is not defined
    - include_role:
        name: mail
      when: run is not defined

    - include_role:
        name: host
        tasks_from: "{{ run }}"
      when: run is defined
    - include_role:
        name: ssl
        tasks_from: "{{ run }}"
      when: run is defined
    - include_role:
        name: mail
        tasks_from: "{{ run }}"
      when: run is defined

    - include_role:
        name: log

