version: "3"

services:
  dev: &service
    build:
      context: .
      target: dev
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      MAILHOST: localhost
    ports:
      - "25:25"
      - "80:80"
      - "587:587"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - "./data/:/virtualmail/data/"
      - "./provision/:/virtualmail/provision/"

  prod:
    <<: *service
    build:
      target: prod
      args: &env
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        MAILHOST: ${MAILHOST}
        SQLITE_DB_PATH: ${SQLITE_DB_PATH}
    environment: *env
    volumes:
      - /virtualmail/data/
      - "${SQLITE_DB_PATH}:/virtualmail/data/app.db"
