---
services:
  inbox:
    labels:
      traefik.enable: true
      traefik.http.routers.inbox.rule: Host(`${MAILHOST:?}`)
      traefik.http.routers.inbox.entrypoints: websecure
      traefik.http.routers.inbox.tls.certresolver: ${CERT_RESOLVER:?}
      traefik.http.services.inbox.loadbalancer.server.port: 8080
    ports: !override []
    networks:
      - service

  cert-sync:
    image: alpine:latest
    depends_on:
      - inbox
    entrypoint: ['sh', '/app/certs/sync.sh', '${MAILHOST:?}']
    volumes:
      - service_certs:/app/service-certs
      - ./cert-sync:/app/certs
    networks:
      - service

volumes:
  service_certs:
    external: true

networks:
  service:
    external: true
