[tool.coverage.run]
omit = ["*/views/*", "*/tests/*"]

[tool.pytest.ini_options]
addopts = "-vvv --cov=inbox --cov=scripts --cov-report=term-missing"
env = ["SQLITE_DB=memory"]

[tool.mypy]
exclude = "venv/"
ignore_missing_imports = true

[tool.ruff]
exclude = ["inbox/views"]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
select = [
    "C90",  # mccabe
    "I",  # isort
    "F",  # flake8
    "E",  # pycodestyle
]
