---
- name: set hostname
  hostname:
    name: "{{ mailhost }}"

- name: set servername
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerName'
    line: "ServerName {{ mailhost }}"

- name: create web directory
  file:
    path: "/var/www/{{ mailhost }}"
    state: directory

- name: create virtualhost file
  template:
    src: virtualhost.conf
    dest: "/etc/apache2/sites-enabled/{{ mailhost }}.conf"
    backup: yes

- name: start apache2  # Needed for the first time
  service:
    name: apache2
    state: started

- name: reload apache2
  service:
    name: apache2
    state: reloaded
