---
- name: set hostname
  hostname:
    name: '{{ config.MAILHOST }}'

- name: set servername
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerName'
    line: 'ServerName {{ config.MAILHOST }}'

- name: create web directory
  file:
    path: '/var/www/{{ config.MAILHOST }}'
    state: directory

- name: create virtualhost file
  template:
    src: virtualhost.conf
    dest: '/etc/apache2/sites-enabled/{{ config.MAILHOST }}.conf'
    backup: true

- name: start apache2  # Needed for the first time
  service:
    name: apache2
    state: started

- name: reload apache2
  service:
    name: apache2
    state: reloaded
