---
- name: set renew certs cron job
  cron:
    name: "renew certs"
    minute: "0"
    hour: "0"
    day: "1"
    job: "certbot renew"

- name: purge old letsencrypt logs
  cron:
    name: "pure old letsencrypt logs"
    minute: "0"
    hour: "4"
    job: "rm /var/log/letsencrypt/letsencrypt.log.1?"
