---
- name: check if cert exists
  stat:
    path: "/etc/letsencrypt/live/{{ mailhost }}/privkey.pem"
  register: letsencrypt_cert
  when: mailhost != "localhost"

- block:
  - name: restart apache2
    service:
      name: apache2
      state: restarted
  - name: certbot
    shell: "certbot --apache -d {{ mailhost }} --non-interactive --agree-tos --email {{ admin_email }}"
  when: mailhost != "localhost" and not letsencrypt_cert.stat.exists
