---
- name: Decide whether to create a new cert
  stat:
    path: /etc/opendkim/keys/{{ hostname }}
  register: opendkim_exists

- block:
    - name: Set current date
      set_fact:
        current_date: '{{ ansible_date_time.date }}'

    - name: Comment out default keytable setting
      lineinfile:
        path: /etc/opendkim/KeyTable
        regexp: _domainkey.{{ hostname }} {{ hostname }}
        state: absent
        backup: true

    - name: Comment out default signingtable setting
      lineinfile:
        path: /etc/opendkim/SigningTable
        regexp: \*@{{ hostname }}
        state: absent
        backup: true

    - name: Delete old trustedhosts entry
      lineinfile:
        path: /etc/opendkim/TrustedHosts
        regexp: \*.{{ hostname }}
        state: absent
        backup: true

    - name: Add trustedhosts entry
      lineinfile:
        path: /etc/opendkim/TrustedHosts
        line: '*.{{ hostname }}'
        create: true
        backup: true

    - name: Add keytable entry
      lineinfile:
        path: /etc/opendkim/KeyTable
        line: '{{ current_date }}._domainkey.{{ hostname }} {{ hostname }}:{{ current_date }}:/etc/opendkim/keys/{{ hostname }}/{{ current_date }}.private'
        create: true
        backup: true

    - name: Add signingtable entry
      lineinfile:
        path: /etc/opendkim/SigningTable
        line: '*@{{ hostname }} {{ current_date }}._domainkey.{{ hostname }}'
        create: true
        backup: true

    - name: Create folder for private/public keypair
      file:
        path: /etc/opendkim/keys/{{ hostname }}
        owner: opendkim
        group: opendkim
        state: directory

    - name: Create keys
      shell: opendkim-genkey -b 2048 -d {{ hostname }} -D /etc/opendkim/keys/{{ hostname }} -s {{ current_date }} -v

    - name: Make OpenDKIM the owner of the keys
      file:
        path: /etc/opendkim/keys/
        recurse: true
        owner: opendkim
        group: opendkim

    - name: Get TXT record
      shell: cat /etc/opendkim/keys/{{ hostname }}/{{ current_date }}.txt
      register: opendkim_key

    - name: Add TXT record for {{ hostname }}
      pause:
        prompt: '{{ opendkim_key.stdout }}'

    - name: Add Postfix to OpenDKIM group
      user:
        name: postfix
        groups: opendkim
        append: true

    - name: Restart OpenDKIM
      command: opendkim -A

  when: not opendkim_exists.stat.exists

- block:
    - name: Check if {{ hostname }} has a txt record
      shell: dig -t txt +short {{ hostname }}
      register: txt_record

    - name: Add TXT record for {{ hostname }}
      pause:
        prompt: 'v=spf1 mx ~all'
      when: txt_record.stdout[1:-1] != 'v=spf1 mx ~all'
