---
name: Deploy to Mail VPS

concurrency: mail

"on":
  push:
    branches:
      - main
      - mail

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate && pip install uv
          . venv/bin/activate && uv pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          . venv/bin/activate && pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/mail' && github.event_name == 'push'

    runs-on: ubuntu-latest
    environment: mail

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH configuration
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} \
            >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Push to remote repository
        env:
          GIT_SSH_COMMAND: ssh -i ~/.ssh/key
        run: |
          git fetch --unshallow
          git remote add deploy \
            ssh://${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:\
          ${{ secrets.REMOTE_PORT }}/srv/git/\
          ${{ github.event.repository.name }}.git
          git push deploy HEAD:main -f

      - name: Clean up
        run: |
          rm -rf ~/.ssh
